# 项目键：在给定的 SonarQube 实例中必须是唯一的。
sonar.projectKey=awesome-demo

# --- 可选属性 ---

# 项目名称，默认使用项目键
#sonar.projectName=My project
# 项目版本，默认是 'not provided'
#sonar.projectVersion=1.0

# 扫描路径是相对于 sonar-project.properties 文件而言的。默认值为 .
sonar.sources=.

# 排除文件 (可选)
sonar.exclusions=**/test/**

# 关键：指定编译后的class文件路径，语言特定配置
sonar.java.binaries=target/classes
sonar.java.test.binaries=target/test-classes

# 源代码编码。默认值为系统默认编码。推荐使用UTF-8
sonar.sourceEncoding=UTF-8